# Generated by Django 6.0.3 on 2026-03-30 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 30, 12, 30, 29, 741960, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
